// General Constants

export const GENEVIZ_FILE_API = 'http://127.0.0.1:5000';
export type GENEVIZ_FILE_API = typeof GENEVIZ_FILE_API;


// General Actions

export const UPLOAD_VNF_TEMPLATE = 'UPLOAD_VNF_TEMPLATE';
export type UPLOAD_VNF_TEMPLATE = typeof UPLOAD_VNF_TEMPLATE;

export const DELETE_VNF_TEMPLATE = 'DELETE_VNF_TEMPLATE';
export type DELETE_VNF_TEMPLATE = typeof DELETE_VNF_TEMPLATE;

export const UPDATE_VNF_PACKAGES = 'UPDATE_VNF_PACKAGES';
export type UPDATE_VNF_PACKAGES = typeof UPDATE_VNF_PACKAGES;

export const SET_VNFD_PROPERTIES = 'SET_VNFD_PROPERTIES';
export type SET_VNFD_PROPERTIES = typeof SET_VNFD_PROPERTIES;

export const RESET_VNFD_PROPERTIES = 'RESET_VNFD_PROPERTIES';
export type RESET_VNFD_PROPERTIES = typeof RESET_VNFD_PROPERTIES;

export const SET_VNFD = 'SET_VNFD';
export type SET_VNFD = typeof SET_VNFD;

export const UPDATED_VNFD_IN_VNF_PACKAGE = 'UPDATED_VNFD_IN_VNF_PACKAGE';
export type UPDATED_VNFD_IN_VNF_PACKAGE = typeof UPDATED_VNFD_IN_VNF_PACKAGE;

export const UPDATE_EDGES = 'UPDATE_EDGES';
export type UPDATE_EDGES = typeof UPDATE_EDGES;

export const UPDATE_NODES = 'UPDATE_NODES';
export type UPDATE_NODES = typeof UPDATE_NODES;

export const SELECT_NODE_OR_EDGE = 'SELECT_NODE_OR_EDGE';
export type SELECT_NODE_OR_EDGE = typeof SELECT_NODE_OR_EDGE;

export const INCREASE_X_OFFSET = 'INCREASE_X_OFFSET';
export type INCREASE_X_OFFSET = typeof INCREASE_X_OFFSET;

// Error Handler Actions

export const FAILED_TO_CREATE_VNFP = 'FAILED_TO_CREATE_VNFP';
export type FAILED_TO_CREATE_VNFP = typeof FAILED_TO_CREATE_VNFP;

export const FAILED_TO_EXTRACT_PROPERTIES_FROM_VNFD = 'FAILED_TO_EXTRACT_PROPERTIES_FROM_VNFD';
export type FAILED_TO_EXTRACT_PROPERTIES_FROM_VNFD = typeof FAILED_TO_EXTRACT_PROPERTIES_FROM_VNFD;

export const FAILED_TO_UPDATE_VNFD_IN_VNF_PACKAGE = 'FAILED_TO_UPDATE_VNFD_IN_VNF_PACKAGE';
export type FAILED_TO_UPDATE_VNFD_IN_VNF_PACKAGE = typeof FAILED_TO_UPDATE_VNFD_IN_VNF_PACKAGE;
