// Constants

export const GENEVIZ_FILE_API = 'http://127.0.0.1:5000';
export type GENEVIZ_FILE_API = typeof GENEVIZ_FILE_API;


// Actions

export const ADD_VNF_TEMPLATE = 'ADD_VNF_TEMPLATE';
export type ADD_VNF_TEMPLATE = typeof ADD_VNF_TEMPLATE;

export const DELETE_VNF_TEMPLATE = 'DELETE_VNF_TEMPLATE';
export type DELETE_VNF_TEMPLATE = typeof DELETE_VNF_TEMPLATE;

export const ADD_SFC_TEMPLATE = 'ADD_SFC_TEMPLATE';
export type ADD_SFC_TEMPLATE = typeof ADD_SFC_TEMPLATE;

export const DELETE_SFC_TEMPLATE = 'DELETE_SFC_TEMPLATE';
export type DELETE_SFC_TEMPLATE = typeof DELETE_SFC_TEMPLATE

export const SET_VNF_PACKAGES = 'SET_VNF_PACKAGES';
export type SET_VNF_PACKAGES = typeof SET_VNF_PACKAGES;

export const SET_VNFD_PROPERTIES = 'SET_VNFD_PROPERTIES';
export type SET_VNFD_PROPERTIES = typeof SET_VNFD_PROPERTIES;

export const RESET_VNFD_PROPERTIES = 'RESET_VNFD_PROPERTIES';
export type RESET_VNFD_PROPERTIES = typeof RESET_VNFD_PROPERTIES;

export const SET_VNFD = 'SET_VNFD';
export type SET_VNFD = typeof SET_VNFD;

export const SET_EDGES = 'SET_EDGES';
export type SET_EDGES = typeof SET_EDGES;

export const SET_NODES = 'SET_NODES';
export type SET_NODES = typeof SET_NODES;

export const SET_GRAPH = 'SET_GRAPH';
export type SET_GRAPH = typeof SET_GRAPH;

export const SELECT_NODE_OR_EDGE = 'SELECT_NODE_OR_EDGE';
export type SELECT_NODE_OR_EDGE = typeof SELECT_NODE_OR_EDGE;

export const INCREASE_X_OFFSET = 'INCREASE_X_OFFSET';
export type INCREASE_X_OFFSET = typeof INCREASE_X_OFFSET;

export const SET_NSD_PROPERTIES = 'SET_NSD_PROPERTIES';
export type SET_NSD_PROPERTIES = typeof SET_NSD_PROPERTIES;

export const HANDLE_VNFD_POPUP = 'HANDLE_VNFD_POPUP';
export type HANDLE_VNFD_POPUP = typeof HANDLE_VNFD_POPUP;

export const HANDLE_SFC_POPUP = 'HANDLE_SFC_POPUP';
export type HANDLE_SFC_POPUP = typeof HANDLE_SFC_POPUP;

export const HANDLE_VNF_LIST = 'HANDLE_VNF_LIST';
export type HANDLE_VNF_LIST = typeof HANDLE_VNF_LIST;

export const SET_BC_PROPERTIES = 'SET_BC_PROPERTIES';
export type SET_BC_PROPERTIES = 'SET_BC_PROPERTIES';

export const SET_SFC_VALIDATION_STATUS = 'SET_SFC_VALIDATION_STATUS';
export type SET_SFC_VALIDATION_STATUS = typeof SET_SFC_VALIDATION_STATUS; 


// Other

export enum SFCValidationStatus {
    SFC_VALIDATION_INITIAL,
    SFC_VALIDATION_PENDING,
    SFC_VALIDATION_VALID,
    SFC_VALIDATION_INVALID,
    SFC_VALIDATION_UNKNOWN,
}