export const UPLOAD_VNF_TEMPLATE = 'UPLOAD_VNF_TEMPLATE';
export type UPLOAD_VNF_TEMPLATE = typeof UPLOAD_VNF_TEMPLATE;

export const DELETE_VNF_TEMPLATE = 'DELETE_VNF_TEMPLATE';
export type DELETE_VNF_TEMPLATE = typeof DELETE_VNF_TEMPLATE;

export const ADD_VNF_TO_SFC = 'ADD_VNF_TO_SFC';
export type ADD_VNF_TO_SFC = typeof ADD_VNF_TO_SFC;

export const REMOVE_VNF_FROM_SFC = 'REMOVE_VNF_FROM_SFC';
export type REMOVE_VNF_FROM_SFC = typeof REMOVE_VNF_FROM_SFC;